### ISSUE TITLE
Ability to whitelist accounts in social aggregator to ensure they go live automatically

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#19] opened 2016-02-26 16:10 UTC
https://akcorg.atlassian.net/browse/AKC2-363

Total Time Spent: 8h

**Comment by spaulenoff** [comment] 2016-02-29 15:29
We need the ability to whitelist certain accounts in social aggregator to ensure they go live automatically.
There are currently a few accounts whitelisted including AKC Dog Lovers

**Comment by spaulenoff** [comment] 2016-02-29 15:30
From Simon Paulenoff 12/17/15 9:10am: Original question from Katherine Grave de Peralta:
"Is there any way to have a social user’s posts go live automatically, without having to publish in the CMS? Asking because akcdoglovers (our handle) is whitelisted but I’m having to approve them as they come in"

**Comment by spaulenoff** [comment] 2016-02-29 15:30
From Kyle Bertelsen 2/8/16 1:58pm: Partially-resolved, but blacklisted and queued images are not appearing in their queues on the backend.
Pulling out of sprint for now.

**Comment by kylejbertelsen** [comment] 2016-04-01 16:49
Doesn't #135 make this ticket pointless? If we're using the photo-galleries, they don't get populated via Social Aggregator.

**Comment by stevepessah** [comment] 2016-04-04 13:13
@spaulenoff what req are missing here?

**Comment by spaulenoff** [comment] 2016-04-04 13:52
@stevepessah No requirements are missing. I will assign to Shailesh

**Comment by kylejbertelsen** [comment] 2016-04-04 15:40
Questions:

A. What is currently happening? If one is whitelisted, do they automatically publish? If one is not whitelisted, do they automatically publish? (test: find a non-whitelisted user, (maybe create one) and test whether their tweets appear automatically. If demonstrably not, then whitelist, and see if NOW they do)

B. What is the desired behavior? @spaulenoff: Please confirm or amend the following: The default behavior is that any given enduser is not whitelisted, and thus their shared images should not be automatically-published. Certain endusers are whitelisted, and as-such, their shared images should be automatically-published. Other certain endusers are blacklisted, and as-such, their shared images should be automatically-rejected. There should be a method for toggling a given enduser between these three states, but when a new enduser is discovered, they should default to default behavior (neither whitelisted, nor blacklisted).

C. What mechanism gathers the content used by this process? @skt2: Make sure that this is documented here (https://akcorg.atlassian.net/wiki/display/BEV/westmemester). By 'documented', I want to see:
1. What action triggers the process that gathers new content? A certain URL is visited? Does it update upon every visit to that URL, or will it only update under certain conditions? What are those conditions? Please list this for every 'type' of implementation of the Social Aggregator -- I know that there are S.A. calls in both Westmemester and on Breed Pages. 
2. Describe the differences between known 'types' of implementation of S.A.
3. Once the content-gathering processes are triggered, describe the files/methods used in processing and storing the data.

**Comment by skt2** [comment] 2016-04-06 16:05
@kylejbertelsen 
A) - Any idea where can I see white listed users and where their tweets are appearing currently, page link might help?

B) - is whitelist user condition working anywhere else except production? I think this is not working locally(it was directly showing the posts when I worked on westmemester long before).

C) - On westmemester it was triggered during page load and there are cache time set to 300(I am not sure this is in seconds or minutes or something else).
- Though I have no idea about breed pages. if you or anyone else know the page where I can check the posts(tweets) are being loaded then please let me know.

**Comment by kylejbertelsen** [comment] 2016-04-07 13:14
@skt2  -- PLEASE take advantage of Slack. These questions could have been cleared-up pretty easily there yesterday.

A) AddOns > Modules > Social Aggregator > View Social Users (button at top)

B) I don't know. You're a developer, and can certainly determine whether it's working or not in a given environment, given the answer in (A) above.

C) I think my (C) above is pretty clear the kind of information I want from you, and where I want those answers recorded.

Breed pages -- the Social Aggregator feeds appear in what Marketing calls the 'UGC' (User Generated Content). Example: on http://www.akc.org/dog-breeds/rottweiler/ the UGC is labeled 'the ROTTWEILER COMMUNITY'. Hover over 'Add My Dog' to see the enduser instructions for getting your photo tweets included.

**Comment by kylejbertelsen** [comment] 2016-04-07 17:33
@spaulenoff: PLEASE verify ASAP:

Desired behavior:
When new user is grabbed from Social Aggregator, that user should be neither whitelisted, nor blacklisted. (@skt2: is there a user status that is neither whitelisted nor blacklisted? Please document this as well)
When new image is grabbed from Social Aggregator, it should be A) queued, if user is neither whitelisted nor blacklisted; B) Unpublished if the user is blacklisted; C) Published if the user is whitelisted;

**Comment by spaulenoff** [comment] 2016-04-07 17:34
@kylejbertelsen confirmed

**Comment by skt2** [comment] 2016-04-07 17:37
@kylejbertelsen User is either Whitelisted or Blacklisted. There is no third status.

**Comment by spaulenoff** [comment] 2016-04-07 17:39
@skt2 There should be three status Whitelisted, neither whitelisted or blacklisted, blacklisted

**Comment by skt2** [comment] 2016-04-08 13:23
@spaulenoff What is the term we want to use for neither whitelisted or blacklisted, as of now I am using Anonymous.

**Comment by spaulenoff** [comment] 2016-04-08 13:35
@skt2 not anonymous, can we just say unassigned?

**Comment by skt2** [comment] 2016-04-08 15:51
@spaulenoff This is taking longer then expected as we want to add new Status(Unassigned) for newly added social user and change the status of image file based on user status.

**Comment by skt2** [comment] 2016-04-11 16:03
Tested here: http://develop2.akc.org/dog-breeds/affenpinscher/
@spaulenoff  For now you can test:
1) when any new social user added in database, his/her status should be "Unassigned"
CMS > Add-ons > Modules > Social Aggregator > View Social Users(button on top-right corner)
2) when any new post added for existing user and if his/her status is "Whitelisted" and then new post should be "Published" by default.
CMS > Add-ons > Modules > Social Aggregator > View Photos/Video(button on top-right corner) -- Make sure you have selected published status in filter dropdown.

**Comment by skt2** [comment] 2016-04-11 16:04
Time spent today: 3h

**Comment by skt2** [comment] 2016-04-11 19:35
NOTE: Changing user status(Whitelisted, Blacklisted and Unassigned) does not change photo status(Published, Unpublished and Queued)

**Comment by skt2** [comment] 2016-04-11 19:37
Note for developers:
Important file for most of queries: /third_party/social_aggregator/mcp.social_aggregator.php
Important function: getAllFilesDbObj()

**Comment by skt2** [comment] 2016-04-11 19:43
After discuss(how we want to show list of photos in CMS) with @kylejbertelsen,
now I am showing the list of photos regardless of user status(Whitelisted, Blacklisted and Unassigned), before it was showing photos for Whitelisted users only.
Though you can always filter photos with photo status(Published, Unpublished and Queued)

**Closed as completed** 2016-04-20 14:04 UTC
Labels: improvement, social media
