### ISSUE TITLE
Ability to create categories based off of AKC Vocabulary 

### ISSUE THREAD

**Issue by elieo** [akcdotorg/akc.org#247] opened 2016-05-10 17:18 UTC
We would like the ability to create new content categories in this /content section that will pull specific article, video and slideshows. The content the categories should be based on the keywords in AKC vocabulary. 

For example, "category A" we can specify to pull content tagged with "puppy" and "category A" would pull content that is tagged in AKC Vocabulary as "puppy".

**Comment by stevepessah** [comment] 2016-05-10 22:26
Duplicate of #205 so closing.

**Closed as completed by stevepessah** 2016-05-10 22:26 UTC
