### ISSUE TITLE
Create global menu option for Generic2 templates

### ISSUE THREAD

**Issue by stevepessah** [akcdotorg/akc.org#3] opened 2016-02-25 21:50 UTC
right now in the generic2 template, you can add a left navigation. This navigation is specific to the page. This causing a major headache when their a group of pages that you need to use the left menu on. (forces you to manually enter in the menu on each page.) 

We need the ability to create a "menu" that can be dynamically pulled in on one page. This way making edits to the menu would be done in one place and synced to all the pages that have that menu selected. 

Kyle proposed solution: Create a 'menu' content type, and add a way to the generic2 pages to select one of those 'menu' types.

**Comment by spaulenoff** [comment] 2016-04-06 19:45
IS this a duplicate of #65?

**Comment by skt2** [comment] 2016-04-20 15:08
So what I have understand so far is we want to add new channel with name something like "Sidebar Navigation"
Then one can add any number of menu items in it with Navigation title and navigation links under it.
e.g. Menu1 title: AENC and links under it is: Back to AENC Homepage
e.g. Menu2 title:  2015 AENC Results and link under it: Best in Show, Reserve Best in Show, Show Summary etc...
Then on article there will be multi-select dropdown so user can select number of menu items he/she want to display in article.
@spaulenoff @kylejbertelsen

**Comment by spaulenoff** [comment] 2016-04-20 15:24
@skt2 Please see some examples of how we want this to function (Sidebars on the left): 
http://www.akc.org/downloadable-forms/
http://www.akc.org/events/aenc/

**Comment by skt2** [comment] 2016-04-21 17:42
**CMS Changes**
**STEP: 1**
CMS > Channels > Create New Channel
Name: Sidebar Navigation
Short Name: sidebar_navigation

**STEP: 2**
CMS > Channels > Channel Fields > Create a new group
Name: Sidebar Navigation

**STEP: 3**
CMS > Channels > Sidebar Navigation > Edit Group Assignments
Channel Field Group: Sidebar Navigation

**STEP: 4**
CMS > Channels > Channel Fields > Sidebar Navigation > Create New Field
Field Type: Grid
Label: Sidebar Navigation Links
Name: sidebar_menu_links_level_1

Configure Grid:
Field 1:
Type: Text Input
Label: Heading
Name: heading

Field 2:
Type: Nolan
Label: Navigation Link Details
Name: sidebar_menu_links_level_2
Column Labels: Title | URL | Target
Column Names: title | url | target
Column Field Types : text_input | text_input | text_input

**STEP 5**
CMS > Channel > Channel Fields > Generic > Create New Field
Type: Relationships
Label: Sidebar Menu
Name: generic_sidebar_menu_links
Select channels to relate: Sidebar Navigation
Limit entries by category: --- Any ---
Authors: --- Any ---
Limit entries by status: Open

**Comment by skt2** [comment] 2016-04-21 18:18
Tested here: http://develop2.akc.org/downloadable-forms/

**Comment by spaulenoff** [comment] 2016-04-28 19:34
Verified on Prod

**Closed as completed by spaulenoff** 2016-04-28 19:34 UTC
Labels: improvement, cms-edits-required, Sidebars

**Comment by skt2** [comment] 2016-04-29 16:20
Total Time Spent: 9h
